name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Deply to Github Container Registry
      run: |
        docker login --username ${{ vars.GHCR_USERNAME }} --password ${{ secrets.GHCR_TOKEN }} ghcr.io
        docker build . --tag ghcr.io/${{ vars.GHCR_USERNAME }}/simple-frontend-app:latest
        docker push ghcr.io/${{ vars.GHCR_USERNAME }}/simple-frontend-app:latest
